#!/bin/bash

for t in 1 2 4 6 8 
do
	for n in  5 10 15 20 250 300 350 400 450 500 1000 1500 2000 2500 10000 11000 12000 13000 14000 15000
	do
		#echo NUMT = $t
		#echo NUMNODES = $n
		/usr/local/common/gcc-7.3.0/bin/g++ -DNUMT=$t -DNUMNODES=$n main_project1.cpp -o main_project1 -O3 -lm -fopenmp
		./main_project1
	done
	echo ""
done
